### ISSUE TITLE
Split init commit and episode code

### ISSUE THREAD

**Issue by m5o** [driftingruby/113-ruby-on-rails-5-2-0-changes-and-new-features#1]
Hey @kobaltz 

Thx for your screencasts. 
Just as an improvement idea, what do you think about do split the initial rails new output from the episode code. Would be easier to track changes. 

Ps. https://depfu.com Is quite new, but maybe worth to keep dependencies up-to-date.

**Comment by kobaltz** [comment]
Thank you for the suggestions. You can always check out [https://www.driftingruby.com](https://www.driftingruby.com) for the show notes which is basically a diff of the two.
